# SPDX-License-Identifier: Apache-2.0
# Modifications Copyright (c) 2026 Actualyze AI
#
# NOTE: This file has been modified by Actualyze AI from the original upstream
# version (magefile/mage). See git history for details.

version: 2

project_name: mage

release:
  github:
    owner: actualyze-ai
    name: mage

builds:
  - binary: mage
    main: .
    ldflags:
      - -s -w
      - -X github.com/actualyze-ai/mage/mage.timestamp={{.Date}}
      - -X github.com/actualyze-ai/mage/mage.commitHash={{.Commit}}
      - -X github.com/actualyze-ai/mage/mage.gitTag={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
      - goos: darwin
        goarch: amd64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}"
    formats:
      - tar.gz
    files:
      - LICENSE

sboms:
  - artifacts: archive
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}.sbom.spdx.json"
    cmd: syft
    args:
      - "$artifact"
      - "--output"
      - "spdx-json=$document"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
